print("Integer von Wahr:", int(True))
print("Integer von Falsch:", int(False))
print("Integer von Kommazahl:", int(123.56))
print("Integer von Text:", int("123"))
print("Kommazahl von Wahr:", float(True))
print("Bool von Kommazahl > 0:", bool(12.34))
print("Bool von Kommazahl = 0:", bool(0.0))
print("BOOL von None:", bool(None))
print("BOOL von leerem Text:", bool(""))
print("BOOL von Text 'False':", bool("False"))
print("Text von Integerzahl:", str(123))
print("Text von Boolean:", str(False))
